services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
      - key: OPENAI_API_KEY
