services:
  - type: web
    name: telegram-ai-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.10
    envVars:
      - key: TELEGRAM_TOKEN
        value: "your-telegram-bot-token-here"
      - key: OPENAI_API_KEY
        value: "your-openai-api-key-here"
