services:
  - type: web
    name: telegram-ai-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: "your-telegram-token"
      - key: OPENAI_API_KEY
        value: "your-openai-key"
    pythonVersion: 3.10
